version: "3.7"

services:
    database:
        image: mysql:5.7
        volumes:
          - /tmp/localstack:/var/lib/mys
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: todo_db
            MYSQL_USER: abdlh
            MYSQL_PASSWORD: password
        networks:
            - clarusnet
    myapp:
        image: 327905352166.dkr.ecr.us-east-1.amazonaws.com/abdlh/todolist:latest
        restart: always
        environment:
            MYSQL_DATABASE_HOST: database
            MYSQL_DATABASE_USER: abdlh
            MYSQL_DATABASE_PASSWORD: password
            MYSQL_DATABASE_DB: todo_db
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - clarusnet

networks:
    clarusnet:
        driver: bridge



        